on:
  push:
  pull_request:
    branches:
      - main

name: build-deploy-book

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2.3.1

      - name: Setup R
        uses: r-lib/actions/setup-r@v1

      - name: Install pandoc
        run: |
          brew install pandoc

      - name: Cache bookdown results
        uses: actions/cache@v2
        with:
          path: docsdown_files
          key: bookdown-${{ hashFiles('**/*Rmd') }}
          restore-keys: bookdown-

      - name: Install packages
        run: |
          R -e 'install.packages("renv")'
          R -e 'renv::restore()'


      - name: Build book
        run: |
          Rscript -e "bookdown::render_book('index.Rmd', quiet = TRUE)"
          rm _book/*.md

      - name: Deploy to github pages
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: _book

