project:
  type: book

freeze: auto
highlight-style: nord
book:
  title: "Notes for example"
  author: "Qiushi Yan"
  date: now
  repo-url: "https://github.com/qiushiyan/example"
  repo-actions: [edit, issue]
  chapters:
    - index.qmd
    - part: "Part"
      chapters:
        - part1.qmd

code-overflow: wrap

format:
  html:
    theme:
      light: [cosmo, style/light.scss]
      dark: [cosmo, style/dark.scss]

jupyter: julia-1.8
editor: visual
